### ISSUE TITLE
mode dosen't start on ubuntu

### ISSUE THREAD

**Issue by MatinHQ** [simonlfc/auzziemod-iw4#2]
Start file
`#!/bin/bash
wine /home/iw4x/servers/trickshot/iw4x.exe -dedicated +set sv_lanonly 1 +set net_port 50913 +exec server.cfg +fs_game mods/auzziemod +loadzone mod +set party_enable 0 +map_rotate`

LOG =>
[console_mp.log](https://github.com/simonlfc/auzziemod-iw4/files/10512328/console_mp.log)

IW4X version: latest dev build (https://updater.xlabs.dev/data-dev/iw4x/iw4x.dll)

**Comment by simonlfc** [comment]
are you missing waypoints in scriptdata? you can get them from [the waypoints repo](https://github.com/simonlfc/auzziemod-iw4-waypoints),  or clone the auzziemod repo and run `git submodule update --init --recursive`
